Separate compoment and eliminate ng-inlude
terranodo/angular-search pull request #34
Opened 2016-09-13 12:06 UTC by Lenninlasd

## What does this PR do?
Remove all `ng-include` code for angular directives.
The idea is to have all components separate each other as semantic and independent elements.

### Related Issue
https://github.com/terranodo/angular-search/issues/32

2016-09-13 14:37 UTC, milafrerichs commented
can/should these directives have their own scope? to not clutter the default scope?

2016-09-13 16:36 UTC, milafrerichs commented on app/components/datepicker/DatepickerDirective.js
> +            InfoService.showInfoPopup(solrHeatmapApp.instructions.datepicker.instruction,
very good. like it, I would even go further and just send the key where the instructions would be found.
e.g.: `datepicker` or `export`

2016-09-15 12:10 UTC, milafrerichs requested changes
Could you have a look into each directive and think about if it would make sense to isolate their scope? 
I think this would declutter the rootScope and make things a little easier.

2016-09-19 02:23 UTC, ingenieroariel commented
What is missing for this to be in a closeable state?

2016-09-19 07:02 UTC, milafrerichs commented
- [ ] the tests that were previously controller tests should be directive tests. 
- [ ] isolate scope where it makes sense. 
- [ ] Fix codeclimate issues (code duplication)

2016-09-19 23:27 UTC, Lenninlasd commented
Hi @milafrerichs , I have some doubts about your comments:
> I think this would declutter the rootScope and make things a little easier.

> can/should these directives have their own scope? to not clutter the default scope?

You are talking about remove the `$rootScope` events? or implement in each directive `this` instead `$scope`, or both?

2016-09-20 08:40 UTC, milafrerichs commented
> You are talking about remove the $rootScope events? or implement in each directive `this` instead `$scope`, or both?

No, I was talking about isolating the scope for each directive. Please read this post and if you have any questions ask me in Slack:
https://www.undefinednull.com/2014/02/11/mastering-the-scope-of-a-directive-in-angularjs/

2016-09-20 13:07 UTC, Lenninlasd commented
Thanks @milafrerichs

2016-09-20 13:32 UTC, milafrerichs commented
@Lenninlasd @ingenieroariel should I help with the directive tests? or can you do it @Lenninlasd ?

2016-09-21 22:13 UTC, Lenninlasd commented
@milafrerichs, @ingenieroariel the isolating scope could be in another PR?

2016-09-22 07:45 UTC, milafrerichs requested changes
The tests life in `tests` folder not inside the `app` folder

what's the reason behind changing the templates from plain `html` to `tpl.html`

2016-09-22 08:44 UTC, milafrerichs commented on Gruntfile.js
> +                base: 'app/components'
please only use `app` and remove the components part. 
add the `components` path part to the directives.

2016-09-22 08:46 UTC, milafrerichs commented on app/components/datepicker/DatepickerDirective.js
>              templateUrl: 'app/components/datepicker/datepicker.html',
why did you not add this template to the `templateCache` ?

2016-09-22 08:49 UTC, milafrerichs commented on karma.conf.js
> +      'tmp/templates.js'
remove this and use `karma-ng-html2js-preprocessor` instead

here are parts of the config that you want to change as well:
```
files [
...
'app/**/*.tpl.html'
],
preprocessors: {
'app/**/*.tpl.html': ['ng-html2js']
},
ngHtml2JsPreprocessor: {
stripPrefix: 'app/',
moduleName: 'templates-components'
}
```

2016-09-22 08:49 UTC, milafrerichs requested changes

2016-09-22 08:55 UTC, milafrerichs commented
Why are you using controllers inside the directives?

2016-09-22 12:29 UTC, milafrerichs commented on tests/service/infoService.spec.js
> +            pending();
replace with:
`solrHeatmapApp.instructions = {'textsearch': 'Test'};`

solrHeatmapApp exists but the text is loaded form a json, we need to simulate this until we have the config service

2016-09-22 12:29 UTC, milafrerichs requested changes

2016-09-22 21:02 UTC, milafrerichs commented on app/components/exportButton/exportButtonDirective.js
> +            controller: ExportController,
why are you using a controller here? can you explain that?

2016-09-22 21:04 UTC, milafrerichs commented on index.html
> +
empty whitespace. pleass remove

2016-09-22 21:05 UTC, milafrerichs requested changes

2016-09-22 21:34 UTC, Lenninlasd commented on app/components/exportButton/exportButtonDirective.js
> +            controller: ExportController,
I'm passing to link function when is required

2016-09-22 21:34 UTC, Lenninlasd commented
Hi @milafrerichs,
- The idea is that each test is linked to its component, in order to make it more visible, easy to maintain, and allows components to be reusable and movable.
I use this style guide:  https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#organizing-tests

- With the .tpl.html extension we can differentiate the files that go to the js templates

2016-09-23 07:05 UTC, milafrerichs commented on app/components/datepicker/DatepickerDirective.js
> +                vm.setInitialDates();
there is no real need for a method that sets the initial date. 
I know that you did not wrote this in the first place but can you change it?

2016-09-23 07:08 UTC, milafrerichs commented on app/components/datepicker/DatepickerDirective.js
> +                    vm.dts = vm.dateOptions.minDate;
can you rename `dts` with `dateStart` or something similar. it is very confusing. we should have better names and not just abbreviations.

2016-09-23 07:09 UTC, milafrerichs commented on app/components/datepicker/DatepickerDirective.js
> +                function stringToDate(dateString) {
can you rename it to `stringToStartEndDateArray` because it does return an Array with start and end date.

2016-09-23 07:22 UTC, milafrerichs requested changes
look really good. 
thanks. just a few small things. should not take long :)

2016-09-23 15:23 UTC, milafrerichs approved these changes

2016-09-23 16:49 UTC, merged