Fix user search and add reset button
terranodo/angular-search pull request #51
Opened 2016-09-26 22:25 UTC by Lenninlasd

## What does this PR do?
Fix user search and add reset button

### Screenshot
![hpqnlovdy2](https://cloud.githubusercontent.com/assets/7197750/18854009/13db3386-840e-11e6-9cc8-73962c99a5ca.gif)

### Related Issue
https://github.com/terranodo/angular-search/issues/35

2016-09-27 13:46 UTC, milafrerichs requested changes

2016-09-27 13:46 UTC, milafrerichs commented on app/components/userFilter/userFilterDirective.js
> +                    HeatMapSourceGenerator.filterObj.setUser(scope.userfilterInput);
please don't set the filterObj like this. use a method for it.
I realised this as well and added a `searchUser` method to `HeatMapSourceGenerator`

2016-09-27 13:46 UTC, milafrerichs commented on tests/service/HeatMapSourceGenerator.spec.js
> +            subject.filterObj.setSearchText('');
please use convenience methods on `HeatMapSourceGenerator` for resetting the search. please don't use `filterObj` directly. I want to replace this eventually.

2016-09-27 13:59 UTC, milafrerichs commented on tests/service/HeatMapSourceGenerator.spec.js
> +            subject.filterObj.setSearchText('');
I'm working on something to replace the `filterObj` will be in the query serialization.

2016-09-27 14:38 UTC, Lenninlasd commented
@milafrerichs, to avoid to create conflicts I'll do a merge with your branch, using your approach.

2016-09-27 23:26 UTC, ingenieroariel commented
why do we need two reset buttons?  Shouldn't there just be one reset for the whole UI? 

/cc @gsolat

2016-09-28 14:39 UTC, Lenninlasd commented
@ingenieroariel @gsolat  visually is frowned upon that a button in other component reset the user in the other side. If it is only one button, I think it must be in other way

2016-09-28 18:02 UTC, Lenninlasd commented
@ingenieroariel @milafrerichs the reset the visual improvements are being done by @gsolat in other branch, what is needed to merge this PR?

2016-09-28 19:18 UTC, milafrerichs commented
wait till the #44 PR is merged for updating the user search and reset. maybe even close this one and work from the other one.

2016-09-28 19:24 UTC, ingenieroariel commented
as discussed, let's create a reset button at the level of the export one.

2016-09-29 07:16 UTC, closed without merging